alias editalias='vim ~/.bash_aliases'
alias ec2ssh='ssh ubuntu@xdmtk.org -i ~/Documents/AWS/UbuntuFinal.pem'
alias suspend='systemctl suspend'
alias colssh='ssh nmartinez@nmartinez.collide.com'
alias thunderbird='thunderbird --safe-mode'
alias closetv='killall teamviewer; sudo killall teamviewerd'
alias taskman='ps -ax | grep'
alias keygenmusic='cd /media/xdmtk/025E9B7F5E9B69E5/Users/overc/Music/keygens/Keygens; mocp .'
