alias editalias='vim ~/.bash_aliases'
alias ec2ssh='ssh ubuntu@xdmtk.org -i ~/Documents/AWS/UbuntuFinal.pem'
alias suspend='systemctl suspend'
alias colssh='ssh nmartinez@nmartinez.collide.com'
alias closetv='killall teamviewer; sudo killall teamviewerd'
alias taskman='ps -ax | rg'
alias keygenmusic='cd /media/xdmtk/025E9B7F5E9B69E5/Users/overc/Music/keygens/Keygens; mocp .'
alias python='python3'
alias run='./a.out'
alias gcc='gcc -g'
alias e='exit'
alias desktop-ssh='ssh xdmtk@192.168.1.123'


# Collide Aliases
alias gotopackage='cd /home/xdmtk/prog/i3-theme-manager'
alias youtube-dl='youtube-dl -x --audio-format mp3'
alias gotosite='cd ~/prog/collide/collide-web/php/'
alias gotojs='cd ~/prog/collide/collide-web/php/public/js'
alias gotoblades='cd ~/prog/collide/collide-web/php/resources/views'
alias gotoscripts='cd ~/scripts/collide-scripts'
alias gotoadmincontrollers='cd /home/xdmtk/prog/collide/collide-web/php/admin/Http/Controllers'
alias greprecur='grep -Rwni'
alias gotocontrollers='cd /home/xdmtk/prog/collide/collide-web/php/app/Http/Controllers'
alias editalias='vim ~/.bash_aliases'
alias gotoadminroutes='cd /home/xdmtk/prog/collide/collide-web/php/admin/Http'
alias gotoroutes='cd /home/xdmtk/prog/collide/collide-web/php/app/Http; vim routes.php'
alias runlocalpull='/home/xdmtk/scripts/collide-scripts/udd-optimized'
alias refreshrc='python /home/xdmtk/.vim/randomColorScheme.py'
alias gotojs='cd /home/xdmtk/prog/collide/collide-web/php/public/js2'
alias log='log --color=always'
alias showlessdiff='git diff --color=always | less'
alias gotogrunt='cd /home/xdmtk/prog/collide/collide-web/php/resources/assets'
alias gotolayouts='cd /home/xdmtk/prog/collide/collide-web/php/resources/views/default/layouts'
alias gotopublic='cd /home/xdmtk/prog/collide/collide-web/php/public'
alias gotodev='cd /usr/sites/dev.collide.com'
alias gotoqa='cd /usr/sites/qa.collide.com'
alias copypages='cp -r /home/xdmtk/collide-pages/js2 /home/xdmtk/prog/collide/collide-web/php/public/'
alias gotoavocado='cd /home/xdmtk/prog/collide/collide-web/php/public/avocado/collide-pages/profile'
alias gotologs='cd /home/xdmtk/prog/collide/collide-web/php/storage/logs'
alias gotomemberscss='cd /home/xdmtk/prog/collide/collide-web/php/public/css'
alias gotocommands='cd /home/xdmtk/prog/collide/collide-web/php/app/Console/Commands'
alias gotoapp='cd /home/xdmtk/prog/collide/collide-web/php/app'
alias gotoservices='cd /home/xdmtk/prog/collide/collide-web/php/app/Services'
alias hard='git reset --hard'
alias gstat='git status'
alias glog='git log --stat --source --graph --oneline'
alias gotoapi='cd /home/xdmtk/prog/collide/collide-web/php/app/Http/Controllers/Api'
alias gotopages='cd /home/xdmtk/prog/collide/collide-pages'
alias gotojslibs='cd /home/xdmtk/prog/collide/collide-web/php/public/assets/js/libs'
alias gototinker='gotosite; php artisan tinker'
alias gotodevscripts='cd /usr/local/etc/collide-scripts/dev'
alias gotovendor='cd /home/xdmtk/prog/collide/collide-web/php/vendor/laravel/framework/src/Illuminate'
alias rmlog='rm -f laravel*'
alias vlog='vim laravel*'
alias e='exit'
alias logviewer='python /home/xdmtk/scripts/collide-scripts/utils/logviewer/logviewer.py'
alias gotologviewer='cd /home/xdmtk/scripts/collide-scripts/utils/logviewer'
alias gotoservices='cd /home/xdmtk/prog/collide/collide-web/php/app/Services'
alias cleangit='git reset --hard; git clean -fd'
alias pagetoweb='/home/xdmtk/scripts/collide-scripts/utils/pages-to-web/ptw.sh'
alias webgrv='gotosite; ~/prog/grv -repoFilePath ~/projects/collide'
alias pagesgrv='gotopages; ~/prog/grv -repoFilePath ~/collide-pages'
alias gc='git commit -am'
alias gp='git push'
alias gpl='git pull'




# Arduino 
alias compile-arduino='arduino-cli compile --fqbn arduino:avr:uno'
alias upload-arduino='sudo arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:uno'
alias read-arduino='sudo cat /dev/ttyACM0'


